# File: .github/workflows/deploy-enterprise-alternative.yml
name: 🔧 Enterprise Deploy - Alternative Methods

on:
  workflow_dispatch:
    inputs:
      deployment_strategy:
        description: 'Choose deployment strategy'
        required: true
        default: 'ftp-direct-ip'
        type: choice
        options:
        - ftp-direct-ip
        - ftp-alt-server
        - network-diagnostic

env:
  NODE_VERSION: '18.x'
  DEPLOYMENT_TIMEOUT: 300000
  HOSTINGER_PRIMARY_IP: '185.239.210.65'
  HOSTINGER_SECONDARY_IP: '153.92.2.12'

jobs:
  # Alternative deployment strategies to bypass 530 errors
  enterprise-deployment-alternative:
    name: 🔧 Alternative Deployment Strategy
    runs-on: ubuntu-latest
    
    steps:
      - name: 📋 Checkout Repository
        uses: actions/checkout@v4
        
      - name: 📦 Setup Node.js Enterprise
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: 📚 Install Dependencies
        run: |
          echo "📚 Installing production dependencies..."
          npm ci
          echo "✅ Dependencies installed successfully"
          
      - name: 🏗️ Build Application
        run: |
          echo "🏗️ Building Next.js application for production..."
          npm run build
          
          # Validate build output
          if [ ! -d "out" ]; then
            echo "❌ Build failed: 'out' directory not created"
            exit 1
          fi
          
          FILE_COUNT=$(find out/ -type f | wc -l)
          echo "✅ Build successful: $FILE_COUNT files generated"
          
      - name: 📦 Prepare Enterprise Deployment Package
        run: |
          echo "📦 Creating enterprise deployment package..."
          mkdir -p deployment
          cp -r out/* deployment/
          
          # Package analysis
          echo "📊 Package Analysis:"
          echo "Files: $(find deployment/ -type f | wc -l)"
          echo "Size: $(du -sh deployment/ | cut -f1)"

      # FTP DIRECT IP DEPLOYMENT
      - name: 🎯 FTP Direct IP Deployment
        if: ${{ github.event.inputs.deployment_strategy == 'ftp-direct-ip' }}
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ env.HOSTINGER_PRIMARY_IP }}
          username: ${{ secrets.HOSTINGER_FTP_USERNAME }}
          password: ${{ secrets.HOSTINGER_FTP_PASSWORD }}
          local-dir: ./deployment/
          server-dir: ./public_html/
          protocol: ftp
          port: 21
          log-level: verbose
          dangerous-clean-slate: true
          timeout: ${{ env.DEPLOYMENT_TIMEOUT }}
          security: loose
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.DS_Store
            **/Thumbs.db
            **/*.map

      # FTP ALTERNATIVE SERVER DEPLOYMENT
      - name: 🔄 FTP Alternative Server Deployment
        if: ${{ github.event.inputs.deployment_strategy == 'ftp-alt-server' }}
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ env.HOSTINGER_SECONDARY_IP }}
          username: ${{ secrets.HOSTINGER_FTP_USERNAME }}
          password: ${{ secrets.HOSTINGER_FTP_PASSWORD }}
          local-dir: ./deployment/
          server-dir: ./public_html/
          protocol: ftp
          port: 21
          log-level: verbose
          dangerous-clean-slate: true
          timeout: ${{ env.DEPLOYMENT_TIMEOUT }}
          security: loose
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.DS_Store
            **/Thumbs.db
            **/*.map

      # NETWORK DIAGNOSTIC MODE
      - name: 🌐 Network Diagnostic Analysis
        if: ${{ github.event.inputs.deployment_strategy == 'network-diagnostic' }}
        run: |
          echo "🌐 ALTERNATIVE NETWORK DIAGNOSTIC"
          echo "================================"
          
          # Test alternative Hostinger endpoints
          SERVERS=(
            "files.hostinger.com"
            "ftp.hostinger.com"
            "${{ env.HOSTINGER_PRIMARY_IP }}"
            "${{ env.HOSTINGER_SECONDARY_IP }}"
          )
          
          echo "📡 Testing alternative Hostinger endpoints..."
          for server in "${SERVERS[@]}"; do
            echo "Testing: $server"
            if timeout 15 bash -c "</dev/tcp/$server/21" 2>/dev/null; then
              echo "  ✅ Port 21 (FTP): OPEN"
              
              # Test basic FTP handshake
              RESPONSE=$(echo "quit" | timeout 10 telnet $server 21 2>/dev/null | head -1 || echo "No response")
              echo "  📝 FTP Response: $RESPONSE"
            else
              echo "  ❌ Port 21 (FTP): CLOSED"
            fi
            echo ""
          done
          
          # GitHub Actions environment info
          echo "🔍 GitHub Actions Environment:"
          echo "Runner IP: $(curl -s ifconfig.me 2>/dev/null || echo 'Unknown')"
          echo "DNS servers: $(cat /etc/resolv.conf | grep nameserver | head -3)"
          echo ""
          
          # Test credential format validation
          echo "🔑 Credential Format Check:"
          echo "✅ Username should be: u[numbers].caiocastilho.com"
          echo "✅ Password should be: FTP-specific password from hPanel"
          echo "✅ Server options: files.hostinger.com, 185.239.210.65, 153.92.2.12"

      # POST-DEPLOYMENT VERIFICATION
      - name: ⏳ File Propagation Wait
        if: ${{ github.event.inputs.deployment_strategy != 'network-diagnostic' }}
        run: |
          echo "⏳ Waiting for file propagation..."
          sleep 60

      - name: 🧪 Verification Suite
        if: ${{ github.event.inputs.deployment_strategy != 'network-diagnostic' }}
        run: |
          echo "🧪 VERIFICATION SUITE"
          echo "===================="
          
          # HTTP Status Check
          STATUS=$(curl -o /dev/null -s -w "%{http_code}" https://caiocastilho.com --connect-timeout 30)
          echo "HTTP Status: $STATUS"
          
          if [ "$STATUS" = "200" ]; then
            echo "✅ Website is accessible"
            echo "✅ Deployment successful!"
          else
            echo "⚠️ Website returned status: $STATUS"
          fi

      # DEPLOYMENT REPORT
      - name: 📊 Alternative Deployment Report
        if: always()
        run: |
          echo "📊 ALTERNATIVE DEPLOYMENT REPORT"
          echo "================================"
          echo "🎯 Strategy used: ${{ github.event.inputs.deployment_strategy }}"
          echo "⏰ Timestamp: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
          echo "🌐 Website: https://caiocastilho.com"
          echo ""
          echo "🔧 Strategy Details:"
          if [ "${{ github.event.inputs.deployment_strategy }}" = "ftp-direct-ip" ]; then
            echo "  - Used direct IP connection to Hostinger"
            echo "  - Server: ${{ env.HOSTINGER_PRIMARY_IP }}"
            echo "  - Bypasses DNS resolution issues"
          elif [ "${{ github.event.inputs.deployment_strategy }}" = "ftp-alt-server" ]; then
            echo "  - Used alternative server IP"
            echo "  - Server: ${{ env.HOSTINGER_SECONDARY_IP }}"
            echo "  - Fallback for primary server issues"
          elif [ "${{ github.event.inputs.deployment_strategy }}" = "network-diagnostic" ]; then
            echo "  - Performed comprehensive network analysis"
            echo "  - Use results to optimize deployment strategy"
          fi
          echo ""
          echo "🚀 Next Steps:"
          echo "  - Test website functionality"
          echo "  - Monitor performance"
          echo "  - Document successful strategy" 