# /.github/workflows/deploy.yml
# Purpose: Automatically deploys the latest changes from the main branch to production.
name: 🚀 Continuous Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-production:
    name: 🚀 Deploy to Production
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      deployment_target: 'Hostinger (Production)'
    secrets:
      HOSTINGER_FTP_USERNAME: ${{ secrets.HOSTINGER_FTP_USERNAME }}
      HOSTINGER_FTP_PASSWORD: ${{ secrets.HOSTINGER_FTP_PASSWORD }} 